### ISSUE TITLE
Compilation error during “make” step

### ISSUE THREAD

**Issue by weiyz19** [maxmouchet/kapar#1]
I'm trying to install kapar following the instruction:
```
./configure --with-scamper="/home/scamper-cvs-20211212e/scamper"
make
```
However the make step doesn;t work. Error message is below:
```
kapar.cc:1648:21: error: no match for ‘operator!=’ (operand types are ‘const Sink’ and ‘const Sink’)
 1648 |     if (debugsubnet != sink) {
      |                     ^~ ~~~~
      |                        |
      |                        const Sink
```
I'm using the C++17 standard. What's the problem?

**Comment by maxmouchet** [comment]
Are you using this repository, or the source from CAIDA?

If you use this repository you shouldn't encounter this issue :)
It's why I created it in the first place: https://github.com/maxmouchet/kapar/commit/29336344c69cdfe953c83dcf596a19f1671ff682
